### PR TITLE
Fix ui defects

### PR DESCRIPTION
**Pull request by pravinrajr9**
Fixing of OSC UI defect #418

## Description
Fixed the OSC UI defect for displaying selection type option parameters correctly,

## Motivation and Context

fixes issue https://github.com/opensecuritycontroller/osc-core/issues/418

## How Has This Been Tested?
Tested manually

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code style guidelines](https://github.com/opensecuritycontroller/community/blob/master/development/eclipse.md) of this project
- [ ] My unit test follow the [Unit test guidelines](https://github.com/opensecuritycontroller/community/blob/master/development/unit_test_guidelines.md)
- [X] Unit test coverage percentage is maintained(increased/remains the same but not decreased)

### CODE REVIEW

**Comment by arvindn05** [comment]
@pravinrajr9 not sure how this fixes the original issue. The original issue is about the text Vm -> VM

**Comment by pravinrajr9** [comment]
@arvindn05 I added this parameter assuming it could reflect the changes immediately since everything was fine in the code. But it worked fine for older version of osc-ui, where I was able to reproduce the issue.  I am not able to reproduce this defect in latest versions of osc-ui. We can close this bug.  It may be a good practice to add this parameter since we want listener to get called immediately for workload selection type, this pull request may be irrelevant to this defect as it can not be reproduced in newer osc versions.

**Comment by arvindn05** [comment]
`https://vaadin.com/forum/#!/thread/2983812/3070078`
@pravinrajr9 Immediate has the cost of as soon as the field changes value, it is sent to the server. 

I think here the combo box results in openstack calls which are expensive. Not having it immediate is better in this case as we make the call only after the user moves away from the combobox.

**Comment by arvindn05** [comment]
@pravinrajr9 Please close the pull request as it seems this is not needed for the bug fix. You can mark the bug as non-issue and post a screenshot there as collateral.

**Pull request closed without merging**
